### ISSUE TITLE
如何登录的

### ISSUE THREAD

**Issue by goodpaperman** [woodheader/jjz#1]
抓包可以获取 authorization 字段，但是过期了怎么办，有办法用账号密码自动登录吗

**Comment by woodheader** [comment]
你好，authorization 字段目前经过测试，是不会过期的，我们几个人的 authorization 已经运行超过了6个月。

**Comment by goodpaperman** [comment]
我提交请求时为何老收到服务器这样的回应：
{
  "msg": "目前办理业务人数较多，请稍后再试。",
  "code": 500
}

**Comment by woodheader** [comment]
如果是在执行 shell 脚本的时候报这个错误，通常是因为你的 header 参数有问题。
可以仔细检查下。

**Comment by goodpaperman** [comment]
感觉是我的请求数据有问题，方便提供一个 apply_data 的模板吗
因为使用同样的 header 访问 statelist 是没有问题的

**Comment by goodpaperman** [comment]
新情况补充：
在 android 上执行脚本可以成功，在 pc 上执行就返回 500，这可能是什么原因

**Comment by goodpaperman** [comment]
搞定了，原来是 Content-Length 没计算对，直接用字符串长度了，晕。。
